FROM golang:1.18 AS build

ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE=on
ENV CGO_ENABLED=0

ENV HOME /app
WORKDIR $HOME

COPY . .

RUN go mod download

RUN go build -o ./test-service ./cmd/testservice/

FROM alpine:latest

COPY --from=build /app/test-service /app/test-service

WORKDIR /app

EXPOSE 80

CMD ["./test-service"]
